# Generated by Django 6.0.6 on 2026-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_fooditem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='nutrition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
