# Generated by Django 6.0.6 on 2026-07-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_fooditem_options_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional Font Awesome icon (e.g. fa-pizza-slice)', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=30, help_text='Preparation time in minutes'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
