# Generated by Django 5.2.5 on 2026-06-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_fooditem_rating'),
        ('orders', '0004_alter_deliveryzone_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='menu.fooditem'),
        ),
    ]
